# -*- coding: utf-8 -*-
"""Copy of sentence_similarity_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-iEqKRVWNhpOnZi_LN3OMbIaC_1FURPS
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer('all-MiniLM-L6-v2')
text1 = input("Enter Text1 : ")
text2 = input("Enter Text2 : ")
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)
similarity = util.cos_sim(embedding1, embedding2)
print("\nSimilarity Score:",round(float(similarity),2))
if similarity > 0.75:
  print("Similarity Level: High")
elif similarity > 0.4:
  print("Similarity Level: Medium")
else:
  print("Similarity Level: Low ")