# -*- coding: utf-8 -*-
"""product_review_simmarizer_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hYLla_JpIU314i-IV-I-Pp2PNJ0DE629
"""

!pip install transformers torch torch pandas
from transformers import pipeline
import pandas as pd

from transformers import pipeline
import pandas as pd

# Load sentiment analysis pipeline
sentiment = pipeline("sentiment-analysis")

reviews = """The laptop starts quickly and works smoothly for daily tasks.
The screen quality is clear and good for watching videos.
Battery backup is average and needs charging often.
The fan makes noise when many apps are running.
Overall, it is a good laptop for students but not for gaming."""

# Split into sentences
sentences = reviews.split(".")

pros = []
cons = []

for s in sentences:
    s = s.strip()
    if s == "":
        continue

    result = sentiment(s)[0]

    if result["label"] == "POSITIVE":
        pros.append(s)
    elif result["label"] == "NEGATIVE":
        cons.append(s)

# Take only first 2 pros and 2 cons AFTER loop
pros = pros[:2]
cons = cons[:2]

# Make lengths equal for DataFrame
max_len = max(len(pros), len(cons))
pros += [""] * (max_len - len(pros))
cons += [""] * (max_len - len(cons))

df = pd.DataFrame({
    "Pros": pros,
    "Cons": cons
})

print(df)